# 홈쇼핑 실적 데이터 전처리

In [3]:
#홈쇼핑실적데이터
df_new = pd.read_excel('C:/Users/SM-PC/Desktop/빅콘2020/01_제공데이터/가공데이터/new실적.xlsx')
df_new

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액
0,2019-06-15 00:00:00,20.0,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,속옷,119000,16517000.0
1,2019-06-15 00:20:00,20.0,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,속옷,119000,44829000.0
2,2019-06-15 00:40:00,20.0,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,속옷,119000,56057000.0
3,2019-06-15 01:00:00,30.0,100374,201202,USPA 남성 폴로셔츠 위켄드 컬렉션 3종,의류,69000,9996000.0
4,2019-06-15 01:00:00,NaN,100374,201206,USPA 여성 폴로셔츠 위켄드 컬렉션 3종,의류,69000,9409000.0
...,...,...,...,...,...,...,...,...
8183,2019-08-31 23:00:00,NaN,100205,200739,보루네오 루나시즌2 유로탑 멀티수납형 LED침대 킹,가구,648000,52265000.0
8184,2019-08-31 23:20:00,20.0,100292,200945,[가이거] 블랙 에디션 다이아몬드 워치(여성용),잡화,178000,7047000.0
8185,2019-08-31 23:20:00,NaN,100292,200944,[가이거] 블랙 에디션 다이아몬드 워치(남성용),잡화,178000,7551000.0
8186,2019-08-31 23:40:00,20.0,100292,200945,[가이거] 블랙 에디션 다이아몬드 워치(여성용),잡화,178000,23624000.0
8187,2019-08-31 23:40:00,NaN,100292,200944,[가이거] 블랙 에디션 다이아몬드 워치(남성용),잡화,178000,16523000.0

In [4]:
#무형 제거
df_new_drop = df_new.drop(index=df_new[(df_new['상품군'] == '무형') & (df_new['취급액'].isnull())].index)
df_new_drop

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액
0,2019-06-15 00:00:00,20.0,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,속옷,119000,16517000.0
1,2019-06-15 00:20:00,20.0,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,속옷,119000,44829000.0
2,2019-06-15 00:40:00,20.0,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,속옷,119000,56057000.0
3,2019-06-15 01:00:00,30.0,100374,201202,USPA 남성 폴로셔츠 위켄드 컬렉션 3종,의류,69000,9996000.0
4,2019-06-15 01:00:00,NaN,100374,201206,USPA 여성 폴로셔츠 위켄드 컬렉션 3종,의류,69000,9409000.0
...,...,...,...,...,...,...,...,...
8183,2019-08-31 23:00:00,NaN,100205,200739,보루네오 루나시즌2 유로탑 멀티수납형 LED침대 킹,가구,648000,52265000.0
8184,2019-08-31 23:20:00,20.0,100292,200945,[가이거] 블랙 에디션 다이아몬드 워치(여성용),잡화,178000,7047000.0
8185,2019-08-31 23:20:00,NaN,100292,200944,[가이거] 블랙 에디션 다이아몬드 워치(남성용),잡화,178000,7551000.0
8186,2019-08-31 23:40:00,20.0,100292,200945,[가이거] 블랙 에디션 다이아몬드 워치(여성용),잡화,178000,23624000.0
8187,2019-08-31 23:40:00,NaN,100292,200944,[가이거] 블랙 에디션 다이아몬드 워치(남성용),잡화,178000,16523000.0

In [5]:
#결측치 채우기
df_all = df_new_drop.fillna(method = 'ffill')
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8030 entries, 0 to 8187
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   방송일시    8030 non-null   datetime64[ns]
 1   노출(분)   8030 non-null   float64
 2   마더코드    8030 non-null   int64
 3   상품코드    8030 non-null   int64
 4   상품명     8030 non-null   object
 5   상품군     8030 non-null   object
 6   판매단가    8030 non-null   int64
 7   취급액     8030 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(2)
memory usage: 564.6+ KB

In [6]:
df_all

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액
0,2019-06-15 00:00:00,20.0,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,속옷,119000,16517000.0
1,2019-06-15 00:20:00,20.0,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,속옷,119000,44829000.0
2,2019-06-15 00:40:00,20.0,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,속옷,119000,56057000.0
3,2019-06-15 01:00:00,30.0,100374,201202,USPA 남성 폴로셔츠 위켄드 컬렉션 3종,의류,69000,9996000.0
4,2019-06-15 01:00:00,30.0,100374,201206,USPA 여성 폴로셔츠 위켄드 컬렉션 3종,의류,69000,9409000.0
...,...,...,...,...,...,...,...,...
8183,2019-08-31 23:00:00,20.0,100205,200739,보루네오 루나시즌2 유로탑 멀티수납형 LED침대 킹,가구,648000,52265000.0
8184,2019-08-31 23:20:00,20.0,100292,200945,[가이거] 블랙 에디션 다이아몬드 워치(여성용),잡화,178000,7047000.0
8185,2019-08-31 23:20:00,20.0,100292,200944,[가이거] 블랙 에디션 다이아몬드 워치(남성용),잡화,178000,7551000.0
8186,2019-08-31 23:40:00,20.0,100292,200945,[가이거] 블랙 에디션 다이아몬드 워치(여성용),잡화,178000,23624000.0
8187,2019-08-31 23:40:00,20.0,100292,200944,[가이거] 블랙 에디션 다이아몬드 워치(남성용),잡화,178000,16523000.0

In [7]:
#csv저장하기
df_all.to_csv('C:/Users/SM-PC/Desktop/빅콘2020/01_제공데이터/가공데이터/무형제거_실적데이터.csv', index = False, encoding='utf-8-sig')

In [9]:
df_all['month'] = [date.strftime("%m") for date in df_all['방송일시']]
df_all

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,month
0,2019-06-15 00:00:00,20.0,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,속옷,119000,16517000.0,06
1,2019-06-15 00:20:00,20.0,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,속옷,119000,44829000.0,06
2,2019-06-15 00:40:00,20.0,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,속옷,119000,56057000.0,06
3,2019-06-15 01:00:00,30.0,100374,201202,USPA 남성 폴로셔츠 위켄드 컬렉션 3종,의류,69000,9996000.0,06
4,2019-06-15 01:00:00,30.0,100374,201206,USPA 여성 폴로셔츠 위켄드 컬렉션 3종,의류,69000,9409000.0,06
...,...,...,...,...,...,...,...,...,...
8183,2019-08-31 23:00:00,20.0,100205,200739,보루네오 루나시즌2 유로탑 멀티수납형 LED침대 킹,가구,648000,52265000.0,08
8184,2019-08-31 23:20:00,20.0,100292,200945,[가이거] 블랙 에디션 다이아몬드 워치(여성용),잡화,178000,7047000.0,08
8185,2019-08-31 23:20:00,20.0,100292,200944,[가이거] 블랙 에디션 다이아몬드 워치(남성용),잡화,178000,7551000.0,08
8186,2019-08-31 23:40:00,20.0,100292,200945,[가이거] 블랙 에디션 다이아몬드 워치(여성용),잡화,178000,23624000.0,08
8187,2019-08-31 23:40:00,20.0,100292,200944,[가이거] 블랙 에디션 다이아몬드 워치(남성용),잡화,178000,16523000.0,08

In [13]:
# continent 컬럼을 선택합니다.
# 컬럼의 값과 조건을 비교합니다.
# 그 결과를 새로운 변수에 할당합니다.
month_07 = df_mom_code_ffill['month'] == '07'

# lifeExp 컬럼을 선택합니다.
# 컬럼의 값과 조건을 비교합니다.
# 그 결과를 새로운 변수에 할당합니다.
furniture = df_mom_code_ffill['group'] == '가구'

# 두가지 조건를 동시에 충족하는 데이터를 필터링하여 새로운 변수에 저장합니다.
furniture_07 = df_mom_code_ffill[month_07 & furniture]

# 결과를 출력합니다.
furniture_07.head(10)

,date,exp_mins,mom_code,code,name,group,price,sales,month
1653,2019-07-01 22:00:00,20.0,100500,201511,(일)삼익가구 어블러 LED 멀티 수납형 침대 슈퍼싱글,가구,499000,11254000.0,07
1654,2019-07-01 22:00:00,20.0,100500,201505,(무)삼익가구 어블러 LED 멀티 수납형 침대 슈퍼싱글,가구,549000,1420000.0,07
1655,2019-07-01 22:00:00,20.0,100500,201512,(일)삼익가구 어블러 LED 멀티 수납형 침대 퀸,가구,549000,5528000.0,07
1656,2019-07-01 22:00:00,20.0,100500,201506,(무)삼익가구 어블러 LED 멀티 수납형 침대 퀸,가구,599000,9017000.0,07
1657,2019-07-01 22:00:00,20.0,100500,201513,(일)삼익가구 어블러 LED 멀티 수납형 침대 킹,가구,599000,7527000.0,07
1658,2019-07-01 22:00:00,20.0,100500,201507,(무)삼익가구 어블러 LED 멀티 수납형 침대 킹,가구,649000,7527000.0,07
1659,2019-07-01 22:20:00,20.0,100500,201511,(일)삼익가구 어블러 LED 멀티 수납형 침대 슈퍼싱글,가구,499000,10012000.0,07
1660,2019-07-01 22:20:00,20.0,100500,201505,(무)삼익가구 어블러 LED 멀티 수납형 침대 슈퍼싱글,가구,549000,11011000.0,07
1661,2019-07-01 22:20:00,20.0,100500,201512,(일)삼익가구 어블러 LED 멀티 수납형 침대 퀸,가구,549000,6903000.0,07
1662,2019-07-01 22:20:00,20.0,100500,201506,(무)삼익가구 어블러 LED 멀티 수납형 침대 퀸,가구,599000,4538000.0,07

In [16]:
# continent 컬럼을 선택합니다.
# 컬럼의 값과 조건을 비교합니다.
# 그 결과를 새로운 변수에 할당합니다.
month_06 = df_mom_code_ffill['month'] == '06'

# lifeExp 컬럼을 선택합니다.
# 컬럼의 값과 조건을 비교합니다.
# 그 결과를 새로운 변수에 할당합니다.
furniture = df_mom_code_ffill['group'] == '가구'

# 두가지 조건를 동시에 충족하는 데이터를 필터링하여 새로운 변수에 저장합니다. (AND)
df_mom_code_ffill = df_mom_code_ffill[month_06 & furniture]

# 결과를 출력합니다.
df_mom_code_ffill

,date,exp_mins,mom_code,code,name,group,price,sales,month
234,2019-06-16 21:20:00,20.0,100205,200733,보루네오 루나 유로탑 멀티수납형 LED 침대 SS 슈퍼싱글,가구,548000,20032000.0,06
235,2019-06-16 21:20:00,20.0,100205,200732,보루네오 루나 유로탑 멀티수납형 LED 침대 Q 퀸,가구,598000,11798000.0,06
236,2019-06-16 21:20:00,20.0,100205,200731,보루네오 루나 유로탑 멀티수납형 LED 침대 K 킹,가구,648000,20060000.0,06
237,2019-06-16 21:40:00,20.0,100205,200733,보루네오 루나 유로탑 멀티수납형 LED 침대 SS 슈퍼싱글,가구,548000,21577000.0,06
238,2019-06-16 21:40:00,20.0,100205,200732,보루네오 루나 유로탑 멀티수납형 LED 침대 Q 퀸,가구,598000,21863000.0,06
...,...,...,...,...,...,...,...,...,...
1562,2019-06-30 20:40:00,20.0,100205,200732,보루네오 루나 유로탑 멀티수납형 LED 침대 Q 퀸,가구,598000,16843000.0,06
1563,2019-06-30 20:40:00,20.0,100205,200731,보루네오 루나 유로탑 멀티수납형 LED 침대 K 킹,가구,648000,14596000.0,06
1564,2019-06-30 21:00:00,20.0,100205,200733,보루네오 루나 유로탑 멀티수납형 LED 침대 SS 슈퍼싱글,가구,548000,30805000.0,06
1565,2019-06-30 21:00:00,20.0,100205,200732,보루네오 루나 유로탑 멀티수납형 LED 침대 Q 퀸,가구,598000,33605000.0,06
1566,2019-06-30 21:00:00,20.0,100205,200731,보루네오 루나 유로탑 멀티수납형 LED 침대 K 킹,가구,648000,34586000.0,06

## 모델링

In [10]:
import pandas as pd
import numpy as np

#홈쇼핑실적데이터
df_excel = pd.read_excel('C:/Users/SM-PC/Desktop/빅콘2020/01_제공데이터/가공데이터/train_modeling.xlsx')
    
df_excel

,노출(분),마더코드,상품코드,판매단가,취급액,요일,시,주문량,월,holiday(includeSS),실제_서울_최고기온,실제_서울_최저기온,실제_서울_강수량(mm),실제_서울_평균풍속(m/s),예보_서울_강수확률,예보_서울_강수량,DATE
0,20,100305,200981,119000,16517000,5,0,138.798319,6,1,27.4,17.9,2.1,2.5,10.337838,0.210526,20190615
1,20,100305,200981,119000,44829000,5,0,376.714286,6,1,27.4,17.9,2.1,2.5,10.337838,0.210526,20190615
2,20,100305,200981,119000,56057000,5,0,471.067227,6,1,27.4,17.9,2.1,2.5,10.337838,0.210526,20190615
3,30,100374,201202,69000,9996000,5,1,144.869565,6,1,27.4,17.9,2.1,2.5,10.337838,0.210526,20190615
4,0,100374,201206,69000,9409000,5,1,136.362319,6,1,27.4,17.9,2.1,2.5,10.337838,0.210526,20190615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8025,0,100205,200739,648000,52265000,5,23,80.655864,8,1,28.9,18.5,0.0,1.8,22.229730,0.000000,20190831
8026,20,100292,200945,178000,7047000,5,23,39.589888,8,1,28.9,18.5,0.0,1.8,22.229730,0.000000,20190831
8027,0,100292,200944,178000,7551000,5,23,42.421348,8,1,28.9,18.5,0.0,1.8,22.229730,0.000000,20190831
8028,20,100292,200945,178000,23624000,5,23,132.719101,8,1,28.9,18.5,0.0,1.8,22.229730,0.000000,20190831
8029,0,100292,200944,178000,16523000,5,23,92.825843,8,1,28.9,18.5,0.0,1.8,22.229730,0.000000,20190831

In [11]:
from sklearn.model_selection import train_test_split

train_data=df_excel.drop('취급액', axis=1)
target_data=df_excel['취급액']

x_train, x_valid, y_train, y_valid=train_test_split(train_data, target_data)
print(train_data.shape, x_train.shape, x_valid.shape)

(8030, 16) (6022, 16) (2008, 16)

In [12]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier()
tree.fit(x_train, y_train)

print('training set accuracy: ', tree.score(x_train, y_train))
print('valid set accuracy: ', tree.score(x_valid, y_valid))

training set accuracy:  1.0
valid set accuracy:  0.12201195219123506

In [13]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(x_train, y_train)

print('training set accuracy: ', tree.score(x_train, y_train))
print('valid set accuracy: ', tree.score(x_valid, y_valid))

KeyboardInterrupt:

## 데이터 전처리

* 코로나 이팩트 추가
* 변수명: corona

In [14]:
import pandas as pd
import numpy as np

#홈쇼핑실적데이터
df = pd.read_excel('C:/Users/SM-PC/Desktop/빅콘2020/01_제공데이터/가공데이터/train.xlsx')
    
df

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,날짜,...,미세먼지(㎍/㎥),오존(ppm),이산화질소농도(ppm),일산화탄소농도(ppm),아황산가스농도(ppm),초미세먼지(㎍/㎥),분류,MONTH,HOUR,DAY
0,17373,2019-06-15 00:00:00,20,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,inner,119000,16517000,2019-06-15,...,36.00,21.36,0.04308,0.01296,0.364,0.0030,f1,6,0,sat
1,17374,2019-06-15 00:20:00,20,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,inner,119000,44829000,2019-06-15,...,36.00,21.36,0.04308,0.01296,0.364,0.0030,f1,6,0,sat
2,17375,2019-06-15 00:40:00,20,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,inner,119000,56057000,2019-06-15,...,36.00,21.36,0.04308,0.01296,0.364,0.0030,f1,6,0,sat
3,17376,2019-06-15 01:00:00,30,100374,201202,USPA 남성 폴로셔츠 위켄드 컬렉션 3종,cloth,69000,9996000,2019-06-15,...,36.00,21.36,0.04308,0.01296,0.364,0.0030,g11,6,1,sat
4,17377,2019-06-15 01:00:00,0,100374,201206,USPA 여성 폴로셔츠 위켄드 컬렉션 3종,cloth,69000,9409000,2019-06-15,...,36.00,21.36,0.04308,0.01296,0.364,0.0030,g11,6,1,sat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8025,25398,2019-08-31 23:00:00,0,100205,200739,보루네오 루나시즌2 유로탑 멀티수납형 LED침대 킹,furniture,648000,52265000,2019-08-31,...,16.56,9.36,0.03184,0.01672,0.384,0.0034,a1,8,23,sat
8026,25399,2019-08-31 23:20:00,20,100292,200945,[가이거] 블랙 에디션 다이아몬드 워치(여성용),etc,178000,7047000,2019-08-31,...,16.56,9.36,0.03184,0.01672,0.384,0.0034,i29,8,23,sat
8027,25400,2019-08-31 23:20:00,0,100292,200944,[가이거] 블랙 에디션 다이아몬드 워치(남성용),etc,178000,7551000,2019-08-31,...,16.56,9.36,0.03184,0.01672,0.384,0.0034,i29,8,23,sat
8028,25401,2019-08-31 23:40:00,20,100292,200945,[가이거] 블랙 에디션 다이아몬드 워치(여성용),etc,178000,23624000,2019-08-31,...,16.56,9.36,0.03184,0.01672,0.384,0.0034,i29,8,23,sat
8029,25402,2019-08-31 23:40:00,0,100292,200944,[가이거] 블랙 에디션 다이아몬드 워치(남성용),etc,178000,16523000,2019-08-31,...,16.56,9.36,0.03184,0.01672,0.384,0.0034,i29,8,23,sat

In [15]:
innner_bdeeing_living = (df['상품군']=='inner') | (df['상품군']=='bedding') | (df['상품군']=='living')
df.loc[innner_bdeeing_living, 'corona'] = 0.25


health = (df['상품군']=='health')
df.loc[health, 'corona'] = 0.198

furniture6 = (df['상품군']=='furniture') & (df['MONTH']==6)
df.loc[furniture6, 'corona'] = 0.222

furniture7 = (df['상품군']=='furniture') & (df['MONTH']==7)
df.loc[furniture7, 'corona'] = 0.217

furniture8 = (df['상품군']=='furniture') & (df['MONTH']==8)
df.loc[furniture8, 'corona'] = 0.227

life6 = (df['상품군']=='life') & (df['MONTH']==6)
df.loc[life6, 'corona'] = 0.217

life7 = (df['상품군']=='life') & (df['MONTH']==7)
df.loc[life7, 'corona'] = 0.225

life8 = (df['상품군']=='life') & (df['MONTH']==8)
df.loc[life8, 'corona'] = 0.233

food6 = (df['상품군']=='food') & (df['MONTH']==6)
df.loc[food6, 'corona'] = 0.214

food7 = (df['상품군']=='food') & (df['MONTH']==7)
df.loc[food7, 'corona'] = 0.224

food8 = (df['상품군']=='food') & (df['MONTH']==8)
df.loc[food8, 'corona'] = 0.251

beauty6 = (df['상품군']=='beauty') & (df['MONTH']==6)
df.loc[beauty6, 'corona'] = 0.238

beauty7 = (df['상품군']=='beauty') & (df['MONTH']==7)
df.loc[beauty7, 'corona'] = 0.249

beauty8 = (df['상품군']=='beauty') & (df['MONTH']==8)
df.loc[beauty8, 'corona'] = 0.262

etc6 = (df['상품군']=='etc') & (df['MONTH']==6)
df.loc[etc6, 'corona'] = 0.245

etc7 = (df['상품군']=='etc') & (df['MONTH']==7)
df.loc[etc7, 'corona'] = 0.254

etc8 = (df['상품군']=='etc') & (df['MONTH']==8)
df.loc[etc8, 'corona'] = 0.25

cloth6 = (df['상품군']=='cloth') & (df['MONTH']==6)
df.loc[cloth6, 'corona'] = 0.248

cloth7 = (df['상품군']=='cloth') & (df['MONTH']==7)
df.loc[cloth7, 'corona'] = 0.252

cloth8 = (df['상품군']=='cloth') & (df['MONTH']==8)
df.loc[cloth8, 'corona'] = 0.2

elec6 = (df['상품군']=='elec') & (df['MONTH']==6)
df.loc[elec6, 'corona'] = 0.229

elec7 = (df['상품군']=='elec') & (df['MONTH']==7)
df.loc[elec7, 'corona'] = 0.24

elec8 = (df['상품군']=='elec') & (df['MONTH']==8)
df.loc[elec8, 'corona'] = 0.232

In [16]:
df

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,날짜,...,오존(ppm),이산화질소농도(ppm),일산화탄소농도(ppm),아황산가스농도(ppm),초미세먼지(㎍/㎥),분류,MONTH,HOUR,DAY,corona
0,17373,2019-06-15 00:00:00,20,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,inner,119000,16517000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.0030,f1,6,0,sat,0.250
1,17374,2019-06-15 00:20:00,20,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,inner,119000,44829000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.0030,f1,6,0,sat,0.250
2,17375,2019-06-15 00:40:00,20,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,inner,119000,56057000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.0030,f1,6,0,sat,0.250
3,17376,2019-06-15 01:00:00,30,100374,201202,USPA 남성 폴로셔츠 위켄드 컬렉션 3종,cloth,69000,9996000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.0030,g11,6,1,sat,0.248
4,17377,2019-06-15 01:00:00,0,100374,201206,USPA 여성 폴로셔츠 위켄드 컬렉션 3종,cloth,69000,9409000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.0030,g11,6,1,sat,0.248
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8025,25398,2019-08-31 23:00:00,0,100205,200739,보루네오 루나시즌2 유로탑 멀티수납형 LED침대 킹,furniture,648000,52265000,2019-08-31,...,9.36,0.03184,0.01672,0.384,0.0034,a1,8,23,sat,0.227
8026,25399,2019-08-31 23:20:00,20,100292,200945,[가이거] 블랙 에디션 다이아몬드 워치(여성용),etc,178000,7047000,2019-08-31,...,9.36,0.03184,0.01672,0.384,0.0034,i29,8,23,sat,0.250
8027,25400,2019-08-31 23:20:00,0,100292,200944,[가이거] 블랙 에디션 다이아몬드 워치(남성용),etc,178000,7551000,2019-08-31,...,9.36,0.03184,0.01672,0.384,0.0034,i29,8,23,sat,0.250
8028,25401,2019-08-31 23:40:00,20,100292,200945,[가이거] 블랙 에디션 다이아몬드 워치(여성용),etc,178000,23624000,2019-08-31,...,9.36,0.03184,0.01672,0.384,0.0034,i29,8,23,sat,0.250
8029,25402,2019-08-31 23:40:00,0,100292,200944,[가이거] 블랙 에디션 다이아몬드 워치(남성용),etc,178000,16523000,2019-08-31,...,9.36,0.03184,0.01672,0.384,0.0034,i29,8,23,sat,0.250

In [17]:
#csv저장하기
df.to_csv('C:/Users/SM-PC/Desktop/빅콘2020/01_제공데이터/가공데이터/train+corona_effect.csv', index = False, encoding='utf-8-sig')