In [1]:
import os
print(os.getcwd())

C:\Users\장세환

In [2]:
os.chdir("E:/bigcontest")
print(os.getcwd())

E:\bigcontest

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv

In [9]:
train= pd.read_excel('./train_ver1.xlsx',header= 0)

In [10]:
train.head()

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,날짜,...,오존(ppm),이산화질소농도(ppm),일산화탄소농도(ppm),아황산가스농도(ppm),초미세먼지(㎍/㎥),분류,MONTH,HOUR,DAY,Active Users
0,17373,2019-06-15 00:00:00,20,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,inner,119000,16517000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,f1,6,0,sat,118574.0
1,17374,2019-06-15 00:20:00,20,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,inner,119000,44829000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,f1,6,0,sat,118574.0
2,17375,2019-06-15 00:40:00,20,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,inner,119000,56057000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,f1,6,0,sat,118574.0
3,17376,2019-06-15 01:00:00,30,100374,201202,USPA 남성 폴로셔츠 위켄드 컬렉션 3종,cloth,69000,9996000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,g11,6,1,sat,118574.0
4,17377,2019-06-15 01:00:00,0,100374,201206,USPA 여성 폴로셔츠 위켄드 컬렉션 3종,cloth,69000,9409000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,g11,6,1,sat,118574.0

In [52]:
b=train.loc[[1,5,3],:]
c=train.loc[[2,3,4],:]
b= pd.concat([b,c]) 
b

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,날짜,...,오존(ppm),이산화질소농도(ppm),일산화탄소농도(ppm),아황산가스농도(ppm),초미세먼지(㎍/㎥),분류,MONTH,HOUR,DAY,Active Users
1,17374,2019-06-15 00:20:00,20,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,inner,119000,44829000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,f1,6,0,sat,118574.0
5,17378,2019-06-15 01:00:00,0,100374,201200,USPA 남성 아동 반팔 폴로셔츠 3종,cloth,59000,1081000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,g11,6,1,sat,118574.0
3,17376,2019-06-15 01:00:00,30,100374,201202,USPA 남성 폴로셔츠 위켄드 컬렉션 3종,cloth,69000,9996000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,g11,6,1,sat,118574.0
2,17375,2019-06-15 00:40:00,20,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,inner,119000,56057000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,f1,6,0,sat,118574.0
3,17376,2019-06-15 01:00:00,30,100374,201202,USPA 남성 폴로셔츠 위켄드 컬렉션 3종,cloth,69000,9996000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,g11,6,1,sat,118574.0
4,17377,2019-06-15 01:00:00,0,100374,201206,USPA 여성 폴로셔츠 위켄드 컬렉션 3종,cloth,69000,9409000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,g11,6,1,sat,118574.0

In [61]:
train1=train.head(0) 
train1=pd.concat([train1 , train[train['상품코드']==goods[1]]])
train1

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,날짜,...,오존(ppm),이산화질소농도(ppm),일산화탄소농도(ppm),아황산가스농도(ppm),초미세먼지(㎍/㎥),분류,MONTH,HOUR,DAY,Active Users
495,17868,2019-06-19 21:00:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,50000,2019-06-19,...,25.64,0.04608,0.01696,0.392,0.00312,a2,6,21,wed,NaN
501,17874,2019-06-19 21:20:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,7005000,2019-06-19,...,25.64,0.04608,0.01696,0.392,0.00312,a2,6,21,wed,127648.0
507,17880,2019-06-19 21:40:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,9320000,2019-06-19,...,25.64,0.04608,0.01696,0.392,0.00312,a2,6,21,wed,127648.0
1756,19129,2019-07-02 23:00:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,6004000,2019-07-02,...,22.16,0.04944,0.01664,0.408,0.00364,a2,7,23,tue,140611.0
1762,19135,2019-07-02 23:20:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,8983000,2019-07-02,...,22.16,0.04944,0.01664,0.408,0.00364,a2,7,23,tue,140611.0
1768,19141,2019-07-02 23:40:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,6004000,2019-07-02,...,22.16,0.04944,0.01664,0.408,0.00364,a2,7,23,tue,140611.0
2580,19953,2019-07-10 23:00:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,50000,2019-07-10,...,5.76,0.02996,0.01072,0.252,0.00296,a2,7,23,wed,NaN
2586,19959,2019-07-10 23:20:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,50000,2019-07-10,...,5.76,0.02996,0.01072,0.252,0.00296,a2,7,23,wed,NaN
2592,19965,2019-07-10 23:40:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,3029000,2019-07-10,...,5.76,0.02996,0.01072,0.252,0.00296,a2,7,23,wed,146122.0
3151,20524,2019-07-15 22:00:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,50000,2019-07-15,...,31.32,0.02780,0.02336,0.512,0.00312,a2,7,22,mon,NaN
3157,20530,2019-07-15 22:20:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,3029000,2019-07-15,...,31.32,0.02780,0.02336,0.512,0.00312,a2,7,22,mon,115963.0
3163,20536,2019-07-15 22:40:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,6004000,2019-07-15,...,31.32,0.02780,0.02336,0.512,0.00312,a2,7,22,mon,115963.0
4043,21416,2019-07-23 19:00:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,50000,2019-07-23,...,17.52,0.01980,0.01932,0.364,0.00400,a2,7,19,tue,NaN
4049,21422,2019-07-23 19:20:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,3027000,2019-07-23,...,17.52,0.01980,0.01932,0.364,0.00400,a2,7,19,tue,142431.0
4055,21428,2019-07-23 19:40:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,11960000,2019-07-23,...,17.52,0.01980,0.01932,0.364,0.00400,a2,7,19,tue,142431.0
4980,22353,2019-08-01 22:00:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,50000,2019-08-01,...,7.80,0.01600,0.01540,0.344,0.00328,a2,8,22,thu,NaN
4986,22359,2019-08-01 22:20:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,6121000,2019-08-01,...,7.80,0.01600,0.01540,0.344,0.00328,a2,8,22,thu,163292.0
4992,22365,2019-08-01 22:40:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,6123000,2019-08-01,...,7.80,0.01600,0.01540,0.344,0.00328,a2,8,22,thu,163292.0
5321,22694,2019-08-04 23:20:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,50000,2019-08-04,...,20.00,0.04376,0.01912,0.416,0.00340,a2,8,23,sun,NaN
5327,22700,2019-08-04 23:40:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,50000,2019-08-04,...,20.00,0.04376,0.01912,0.416,0.00340,a2,8,23,sun,NaN
5333,22706,2019-08-05 00:00:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,3085000,2019-08-05,...,29.08,0.03380,0.02188,0.440,0.00344,a2,8,0,mon,169626.0
5840,23213,2019-08-09 23:00:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,50000,2019-08-09,...,18.20,0.01956,0.02196,0.352,0.00420,a2,8,23,fri,NaN
5846,23219,2019-08-09 23:20:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,6123000,2019-08-09,...,18.20,0.01956,0.02196,0.352,0.00420,a2,8,23,fri,153760.0
5852,23225,2019-08-09 23:40:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,50000,2019-08-09,...,18.20,0.01956,0.02196,0.352,0.00420,a2,8,23,fri,NaN
6247,23620,2019-08-13 19:00:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,3088000,2019-08-13,...,14.68,0.02744,0.01940,0.380,0.00364,a2,8,19,tue,148160.0
6253,23626,2019-08-13 19:20:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,50000,2019-08-13,...,14.68,0.02744,0.01940,0.380,0.00364,a2,8,19,tue,NaN
6259,23632,2019-08-13 19:40:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,50000,2019-08-13,...,14.68,0.02744,0.01940,0.380,0.00364,a2,8,19,tue,NaN
6709,24082,2019-08-17 22:20:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,50000,2019-08-17,...,20.12,0.05532,0.01328,0.452,0.00412,a2,8,22,sat,NaN
6715,24088,2019-08-17 22:40:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,3085000,2019-08-17,...,20.12,0.05532,0.01328,0.452,0.00412,a2,8,22,sat,152315.0
6721,24094,2019-08-17 23:00:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,3085000,2019-08-17,...,20.12,0.05532,0.01328,0.452,0.00412,a2,8,23,sat,152315.0
7031,24404,2019-08-20 23:00:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,3085000,2019-08-20,...,19.16,0.04172,0.01900,0.440,0.00356,a2,8,23,tue,142358.0
7037,24410,2019-08-20 23:20:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,3085000,2019-08-20,...,19.16,0.04172,0.01900,0.440,0.00356,a2,8,23,tue,142358.0
7043,24416,2019-08-20 23:40:00,0,100203,200711,(일)[보루네오] 피올레 천연소가죽 소파 6인용,furniture,1199000,50000,2019-08-20,...,19.16,0.04172,0.01900,0.440,0.00356,a2,8,23,tue,NaN

In [60]:
goods[1]

200711

In [56]:
train1=train.head(0) 
train1=pd.concat([train1, train.loc[[1],:]])
train1

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,날짜,...,오존(ppm),이산화질소농도(ppm),일산화탄소농도(ppm),아황산가스농도(ppm),초미세먼지(㎍/㎥),분류,MONTH,HOUR,DAY,Active Users
1,17374,2019-06-15 00:20:00,20,100305,200981,오모떼 미라클쉐이핑 브라팬티 시즌3,inner,119000,44829000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,f1,6,0,sat,118574.0

In [18]:
goods=list(set(train['상품코드']))
goods

[200707,
 200711,
 200731,
 200732,
 200733,
 200735,
 200737,
 200739,
 200759,
 200766,
 200767,
 200769,
 200776,
 200777,
 200779,
 200780,
 200783,
 200784,
 200796,
 200797,
 200798,
 200807,
 200814,
 200816,
 200817,
 200818,
 200820,
 200823,
 200839,
 200841,
 200852,
 200854,
 200864,
 200868,
 200870,
 200890,
 200893,
 200894,
 200895,
 200904,
 200905,
 200906,
 200909,
 200910,
 200911,
 200913,
 200914,
 200918,
 200928,
 200931,
 200936,
 200939,
 200944,
 200945,
 200946,
 200947,
 200969,
 200972,
 200975,
 200976,
 200981,
 200982,
 200983,
 200984,
 200990,
 200992,
 200993,
 201005,
 201009,
 201032,
 201034,
 201038,
 201040,
 201063,
 201064,
 201067,
 201074,
 201081,
 201088,
 201089,
 201124,
 201125,
 201128,
 201129,
 201131,
 201133,
 201136,
 201137,
 201140,
 201141,
 201144,
 201200,
 201202,
 201204,
 201206,
 201257,
 201280,
 201281,
 201282,
 201285,
 201287,
 201296,
 201297,
 201302,
 201303,
 201305,
 201315,
 201318,
 201320,
 201321,
 201327,
 201328,
 201345,
 201347,
 201361,
 201362,
 201363,
 201364,
 201365,
 201369,
 201371,
 201373,
 201375,
 201376,
 201377,
 201378,
 201379,
 201396,
 201402,
 201403,
 201407,
 201408,
 201419,
 201421,
 201429,
 201435,
 201436,
 201446,
 201452,
 201455,
 201469,
 201472,
 201477,
 201479,
 201481,
 201487,
 201489,
 201501,
 201505,
 201506,
 201507,
 201511,
 201512,
 201513,
 201519,
 201568,
 201569,
 201570,
 201575,
 201582,
 201584,
 201586,
 201590,
 201605,
 201607,
 201608,
 201609,
 201610,
 201619,
 201620,
 201621,
 201630,
 201631,
 201666,
 201667,
 201669,
 201682,
 201710,
 201711,
 201712,
 201713,
 201720,
 201721,
 201722,
 201735,
 201762,
 201763,
 201764,
 201765,
 201772,
 201774,
 201775,
 201806,
 201807,
 201837,
 201838,
 201839,
 201847,
 201850,
 201854,
 201855,
 201856,
 201857,
 201858,
 201870,
 201887,
 201888,
 201890,
 201903,
 201911,
 201912,
 201915,
 201917,
 201918,
 201920,
 201921,
 201924,
 201932,
 201933,
 201934,
 201935,
 201937,
 201939,
 201941,
 201944,
 201945,
 201946,
 201962,
 201964,
 201967,
 201974,
 201977,
 201980,
 202003,
 202011,
 202013,
 202019,
 202020,
 202021,
 202022,
 202026,
 202030,
 202031,
 202032,
 202034,
 202035,
 202037,
 202045,
 202047,
 200000,
 202055,
 200013,
 200014,
 202066,
 200024,
 202073,
 202074,
 202075,
 200028,
 200029,
 200031,
 200032,
 202085,
 200038,
 200040,
 202089,
 200042,
 200041,
 200047,
 200048,
 200049,
 200056,
 202106,
 202109,
 202111,
 200075,
 200076,
 200077,
 200078,
 200080,
 202130,
 200082,
 202132,
 200084,
 200085,
 200087,
 200089,
 202138,
 202139,
 200090,
 200093,
 200094,
 200095,
 202143,
 200097,
 200098,
 202141,
 200091,
 200100,
 200101,
 200103,
 200104,
 200105,
 200106,
 200107,
 200108,
 200109,
 200110,
 200111,
 200112,
 200113,
 200115,
 200122,
 202173,
 200126,
 202176,
 202180,
 200139,
 202187,
 202189,
 200141,
 200140,
 202193,
 200149,
 200150,
 200151,
 200154,
 202203,
 202204,
 202205,
 200158,
 200162,
 200163,
 200166,
 200167,
 200170,
 200171,
 202220,
 202218,
 200174,
 200175,
 202221,
 202219,
 202228,
 202232,
 202234,
 202236,
 200189,
 202239,
 202248,
 202249,
 200202,
 202250,
 202251,
 200201,
 202254,
 202255,
 202256,
 202253,
 202260,
 200215,
 202263,
 202266,
 200220,
 202268,
 202270,
 200223,
 202272,
 202273,
 202274,
 200231,
 200232,
 200233,
 200234,
 200235,
 200237,
 202286,
 202287,
 200240,
 202289,
 202290,
 200239,
 200244,
 200238,
 200254,
 202304,
 202305,
 202306,
 202307,
 202308,
 202309,
 202310,
 202311,
 202312,
 200265,
 202314,
 202315,
 202316,
 200269,
 202317,
 200271,
 202313,
 200275,
 200276,
 200279,
 200282,
 200283,
 200285,
 200286,
 202338,
 202339,
 202340,
 202341,
 202342,
 202343,
 202344,
 202345,
 202346,
 202347,
 202348,
 200302,
 200303,
 202350,
 202351,
 202352,
 202357,
 202379,
 200335,
 202384,
 202385,
 202388,
 200342,
 200343,
 200345,
 200353,
 200354,
 200356,
 202412,
 202415,
 202416,
 202418,
 200372,
 200373,
 200374,
 202422,
 202429,
 202434,
 200390,
 200391,
 200392,
 200393,
 202444,
 202449,
 202452,
 202453,
 200406,
 200407,
 200408,
 200409,
 200410,
 202461,
 202462,
 202467,
 202470,
 202473,
 202474,
 202475,
 200431,
 202480,
 202481,
 202482,
 200435,
 202484,
 200436,
 200440,
 202489,
 200444,
 200445,
 202494,
 202493,
 202492,
 200450,
 202500,
 200453,
 200454,
 202501,
 202504,
 200457,
 200458,
 202510,
 200464,
 200465,
 200468,
 200469,
 200470,
 200471,
 200472,
 200473,
 200474,
 200475,
 200476,
 200477,
 200482,
 200483,
 200485,
 200489,
 200490,
 200491,
 200498,
 200502,
 200503,
 200507,
 200511,
 200512,
 200517,
 200520,
 200521,
 200523,
 200525,
 200526,
 200532,
 200533,
 200536,
 200537,
 200538,
 200539,
 200540,
 200541,
 200542,
 200543,
 200544,
 200545,
 200549,
 200550,
 200552,
 200556,
 200557,
 200558,
 200562,
 200563,
 200575,
 200576,
 200577,
 200578,
 200579,
 200581,
 200583,
 200584,
 200585,
 200587,
 200589,
 200592,
 200593,
 200595,
 200596,
 200610,
 200612,
 200613,
 200614,
 200615,
 200618,
 200624,
 200256,
 200629,
 200630,
 200631,
 200257,
 200632,
 200634,
 200636,
 200637,
 200638,
 200640,
 200641,
 200642,
 200644,
 200645,
 200649,
 200655,
 200657,
 200658,
 200659,
 200662,
 200663,
 200667,
 200671,
 200678,
 200679,
 200680,
 200681,
 200682,
 200683,
 200685,
 200686,
 200690,
 200694,
 200703]

# 20분,40분,60분 데이터 셋 구분

In [62]:
train1=train.head(0) # 20분
train2=train.head(0) # 40분 
train3=train.head(0) # 60분


for i in range(len(goods)):
    count=0
    for j in range(len(train)):
        if goods[i] == train['상품코드'][j]:
            count=+1
    if count==1:
        train1=pd.concat([train1 , train[train['상품코드']==goods[i]]])
    elif count==2:
        train2=pd.concat([train2 , train[train['상품코드']==goods[i]]])
    else:    
        train3=pd.concat([train3 , train[train['상품코드']==goods[i]]])

In [65]:
train1.loc[[17,18,19,20,21],:]

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,날짜,...,오존(ppm),이산화질소농도(ppm),일산화탄소농도(ppm),아황산가스농도(ppm),초미세먼지(㎍/㎥),분류,MONTH,HOUR,DAY,Active Users
17,17390,2019-06-15 07:00:00,0,100067,200166,무이자 캐리어 벽걸이에어컨 7형 ARC07VBC,elec,749000,50000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,b3,6,7,sat,NaN
18,17391,2019-06-15 07:15:00,15,100067,200170,일시불 캐리어 벽걸이에어컨 6형 ARC06NQT,elec,509000,3981000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,b3,6,7,sat,118574.0
19,17392,2019-06-15 07:15:00,0,100067,200162,무이자 캐리어 벽걸이에어컨 6형 ARC06NQT,elec,539000,11511000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,b3,6,7,sat,118574.0
20,17393,2019-06-15 07:15:00,0,100067,200174,일시불 캐리어 벽걸이에어컨 7형 ARC07VBC,elec,709000,5529000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,b3,6,7,sat,118574.0
21,17394,2019-06-15 07:15:00,0,100067,200166,무이자 캐리어 벽걸이에어컨 7형 ARC07VBC,elec,749000,1518000,2019-06-15,...,21.36,0.04308,0.01296,0.364,0.003,b3,6,7,sat,118574.0