### 타방송사 편성표를 통한 feature 추가

In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from matplotlib import font_manager, rc 
font_path = "C:\\Users\\이혜림\\Desktop\\Bita5/malgun.ttf" 
font_name = font_manager.FontProperties(fname=font_path).get_name()
rc("font",family=font_name)

In [6]:
# 크롤링한 데이터 정제 함수
def make_tv(data=tv):
    tv_data = pd.DataFrame()
    start_times = []
    end_times = []
    names = []
    prices = []
    day = []
    date = pd.date_range(start="2019-06-15", end="2019-08-31",freq="D")
    
    # 하루마다 돌면서 각 시간대의 데이터 추출
    for idx_d, one_day in enumerate(data):
        time = one_day[0].split("\n")[-3:]# 첫번째 요소에서는 시간만 추출
        start_times.append(time[0]); end_times.append(time[2])
        
        containers = list(map(lambda x: x.split("\n"), one_day[1:])) # 여러 정보가 담겨있는 container
        
        for idx, container in enumerate(containers):
            name, price, time = container[1],container[2], container[-3:]
            names.append(name); prices.append(price) 
            if idx!=len(containers)-1: # 하루 중 맨 마지막 시간대의 정보에는 시간이 포함되어 있지 않기 때문
                start_times.append(time[0]), end_times.append(time[2]) 
            day.append(date[idx_d])
        
    tv_data["상품명"]=names
    tv_data["가격"]=prices
    tv_data["시작시간"]=start_times
    tv_data["종료시간"]=end_times
    tv_data["날짜"]=day
    
    return tv_data

In [7]:
gs_tv = make_tv(tv)

In [8]:
gs_tv

,상품명,가격,시작시간,종료시간,날짜
0,모두투어 큐슈 상담예약,상담신청,00:25,01:00,2019-06-15
1,청정 남극바다 크릴에서 추출한 100% 크릴오일 크릴56 (6개월분),"179,000원",01:00,02:00,2019-06-15
2,장기무이자 20개월제메이스 14K 빈티지코인 롱 목걸이 2종(14K골드 4.5g),"399,000원",02:00,03:00,2019-06-15
3,엘르 노와이어 브라팬티속옷,"111,200원",03:00,04:00,2019-06-15
4,"1종당 26,334원꼴! 11대 퍼포먼스, 시원함과 편안함에 특화된 바지NEW 헨리...","69,000원",04:00,05:00,2019-06-15
...,...,...,...,...,...
1940,롯데관광 서유럽 4국 상담예약,상담신청,18:40,19:30,2019-08-31
1941,바디프랜드 안마의자 렌탈,상담신청,19:30,20:30,2019-08-31
1942,★사상최초 1박스 더! 특집한정★ 명절선물은 정관장!정관장 화애락큐 6박스+1박스 ...,"525,000원",20:30,21:30,2019-08-31
1943,LG전자 정수기 상담예약,상담신청,21:30,22:30,2019-08-31
1944,라삐아프 19FW 최신상 새틴스커트 2종라삐아프 19FW 새틴스커트 2종,"79,900원",22:30,01:00,2019-08-31

In [10]:
cj_tv = make_tv(tv)

In [11]:
cj_tv

,상품명,가격,시작시간,종료시간,날짜
0,[프라다] 다이어그램 크로스백 1BH083,"1,289,000원",02:10,05:30,2019-06-15
1,<1사1명품> 오토핏 휴대폰 무선충전 거치대 1+1,"59,900원",05:30,06:00,2019-06-15
2,윌슨 19SS 울트라-쿨 5종 패키지 남성 [자켓+티셔츠3종+팬츠],"63,500원",06:00,07:20,2019-06-15
3,[피부가 숨쉬는 커버] 동국제약 마데카커버크림 마스크 구성,"89,000원",07:20,08:20,2019-06-15
4,[굿라이프단독] 365일 숙성노니 이츠코어 노니365 x 10박스,"297,000원",08:20,10:20,2019-06-15
...,...,...,...,...,...
1488,[NEW최신상] 셀리턴 LED 마스크 렌탈,상담신청,17:40,18:40,2019-08-31
1489,삼성전자 가전 패키지 렌탈 서비스,상담신청,19:30,20:30,2019-08-31
1490,M 가누다 골드라벨 라르고 [2세트]베개2+냅1,"288,000원",20:30,21:30,2019-08-31
1491,CJ단독] 이태리 직수입 바게지 스폰지 마스크 4+1통 패키지,"99,000원",21:30,22:30,2019-08-31
1492,[A+G] 엣지 FALL19 셋업 수트 4종,"178,000원",22:30,01:00,2019-08-31

In [77]:
lotte_tv =make_tv(tv)

In [12]:
Train = pd.read_csv("./Train.csv")
data = pd.read_csv("./정리데이터/prepared.csv")

In [290]:
lotte_tv = pd.read_csv("./타방송편성/lotte.csv")

In [395]:
sale_words = ["세일","할인","한정","특집","특가","최저가","인하","1+1", "SALE"]

def is_hot_deal(x):
    for w in sale_words:
        if w in x:
            return True
        else:
            pass
    return False
        
def hot_preprocessing(data):
    hot_deal_data = data[data["상품명"].apply(is_hot_deal)] # 핫딜인 상품만을 추출
    
    hot_deal_bool = hot_deal_data[["날짜"]]
    hot_deal_bool["시"] = hot_deal_data["시작시간"].apply(lambda x: x[:2]).astype(int)
    hot_deal_bool["핫딜유무"]=1
    
    return hot_deal_bool

In [396]:
lotte_hot_bool = hot_preprocessing(lotte_tv)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

In [397]:
gs_hot_bool = hot_preprocessing(gs_tv)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

In [299]:
new_data_gs = data.merge(gs_hot_bool, on=["시","날짜"], how="left").fillna(0)

In [278]:
new_data_gs.loc[(new_data_gs["요일"]==5)|(new_data_gs["요일"]==6),:].groupby("핫딜유무").mean()

,노출(분),마더코드,상품코드,판매단가,취급액,요일,시,주문량,holiday,월,...,예보_일산_일최저기온,예보_수원_강수확률,예보_수원_강수량,예보_수원_일최고기온,예보_수원_일최저기온,Active Users,일,서울풍속,수원풍속,일산풍속
핫딜유무,,,,,,,,,,,,,,,,,,,,,
0,11.522222,100335.186957,201057.801449,483959.202899,2.461355e+07,5.479227,14.099517,321.507137,0.0,7.069565,...,20.654982,18.237205,1.511232,30.227918,21.414463,134349.430918,18.210145,2.245706,1.757162,1.896498
1,11.745098,100410.301961,201267.050980,302180.980392,2.494174e+07,5.541176,13.294118,366.750069,0.0,7.372549,...,21.705882,18.742978,1.363674,31.427864,22.412990,139811.207843,16.223529,2.467817,1.844046,2.002387

In [398]:
cj_hot_bool = hot_preprocessing(cj_tv)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

In [399]:
cj_hot_bool["날짜"]= cj_hot_bool["날짜"].astype(str)

In [400]:
total_hot_bool = pd.concat([cj_hot_bool, gs_hot_bool, lotte_hot_bool], axis=0)

In [361]:
new_data = data.merge(total_hot_bool, on=["시","날짜"], how="left").fillna(0)

In [277]:
new_data_gs.groupby("핫딜유무").mean()

,노출(분),마더코드,상품코드,판매단가,취급액,요일,시,주문량,holiday,월,...,예보_일산_일최저기온,예보_수원_강수확률,예보_수원_강수량,예보_수원_일최고기온,예보_수원_일최저기온,Active Users,일,서울풍속,수원풍속,일산풍속
핫딜유무,,,,,,,,,,,,,,,,,,,,,
0,11.984366,100368.222752,201141.959649,389216.177784,2.269289e+07,3.039756,14.080852,325.663919,0.015337,7.179422,...,21.181216,23.648705,2.992846,30.258683,22.017769,141893.290649,17.416170,2.160719,1.643449,1.775736
1,11.795876,100369.423711,201141.261856,368783.453608,2.213519e+07,3.079381,14.350515,329.653487,0.006186,7.279381,...,21.480653,21.735047,2.553635,30.807216,22.316723,144683.656701,14.847423,2.089463,1.580536,1.720222

In [276]:
new_data_cj.groupby(["핫딜유무"]).mean()

,노출(분),마더코드,상품코드,판매단가,취급액,요일,시,주문량,holiday,월,...,예보_일산_일최저기온,예보_수원_강수확률,예보_수원_강수량,예보_수원_일최고기온,예보_수원_일최저기온,Active Users,일,서울풍속,수원풍속,일산풍속
핫딜유무,,,,,,,,,,,,,,,,,,,,,
0,11.960776,100368.537666,201141.605353,386990.505523,2.265272e+07,3.029595,14.124894,324.639237,0.013311,7.182243,...,21.169132,23.279346,2.857411,30.282933,22.006124,142064.961059,17.139337,2.132831,1.617117,1.748629
1,11.996732,100367.442810,201148.264706,388974.101307,2.234841e+07,3.259804,13.947712,340.485601,0.024510,7.308824,...,21.803717,24.954912,3.902220,30.849463,22.629085,144163.522876,16.395425,2.381252,1.863793,2.014736

In [310]:
new_data.loc[(new_data["요일"]==5)|(new_data["요일"]==6),:].groupby(["시"])["주문량"].mean()

시
0     202.612713
1     220.019680
6     355.445472
7     494.769237
8     462.790102
9     299.831219
10    229.754045
11    238.034543
12    348.989401
13    771.419234
14    423.784343
15    545.394952
16    483.142511
17    937.821413
18    427.532311
19    271.980710
20    280.402433
21    146.013982
22     53.746030
23     89.367345
Name: 주문량, dtype: float64

In [401]:
hot = total_hot_bool.groupby(["날짜","시"]).count().reset_index()

In [309]:
new_data.loc[(new_data["요일"]==5)|(new_data["요일"]==6),:].groupby(["시","핫딜유무"]).mean()

             노출(분)           마더코드           상품코드          판매단가           취급액  \
시  핫딜유무
0  0     15.238095  100389.035714  201319.107143  9.552976e+04  1.505474e+07
1  0     11.101695  100397.016949  201230.949153  1.404627e+05  1.016912e+07
   1     12.843750  100323.078125  201027.375000  5.670938e+04  1.349431e+07
6  0     17.727273  100545.272727  201656.431818  4.731591e+04  1.744775e+07
   1     15.000000  100236.187500  200839.437500  7.241250e+04  1.534602e+07
7  0     15.000000  100426.107143  201321.369048  1.523685e+05  2.805188e+07
   1     13.333333  100344.333333  201085.666667  5.320000e+04  2.268078e+07
8  0     15.692308  100616.861538  201851.861538  7.504615e+04  3.957540e+07
   1      9.473684  100329.026316  200978.710526  6.945368e+05  2.405932e+07
9  0     12.626263  100463.434343  201427.636364  6.570222e+05  3.060792e+07
   1     13.333333  100511.000000  202132.000000  1.190000e+05  2.898089e+07
10 0     10.423729  100304.694915  200941.805085  9.216263e+05  2.747674e+07
   1     13.333333  100566.666667  201689.000000  4.523333e+04  3.207322e+07
11 0      9.516129  100164.379032  200497.612903  6.482137e+05  2.316658e+07
   1      7.500000  100182.000000  200614.875000  1.285000e+05  1.623558e+07
12 0      9.892157  100309.294118  200924.823529  1.723794e+05  2.218229e+07
   1      8.108108  100616.054054  201810.135135  1.346892e+05  1.843784e+07
13 0     17.368421  100428.000000  201349.289474  6.078421e+04  4.670558e+07
   1     15.652174  100545.260870  201636.065217  6.362935e+04  3.750907e+07
14 0     13.571429  100286.928571  200876.000000  8.425357e+04  3.319442e+07
   1      7.500000  100389.125000  201137.500000  1.355812e+05  1.878356e+07
15 0     14.430380  100309.063291  200993.645570  1.733038e+05  3.941833e+07
   1     10.344828  100600.931034  201764.862069  1.086945e+06  2.450114e+07
16 0     11.400000  100420.680000  201325.400000  1.117360e+05  3.174890e+07
   1      9.600000  100519.080000  201579.240000  1.442160e+05  3.112340e+07
17 0     14.782609  100440.391304  201399.739130  1.032826e+05  4.002712e+07
   1     20.000000  100117.000000  200393.000000  4.206667e+04  4.886767e+07
18 0     19.354839  100416.806452  201415.193548  3.025161e+04  1.996523e+07
19 0     12.180851  100431.638298  201372.127660  1.518309e+05  1.623676e+07
   1     18.571429  100403.928571  201532.928571  3.022143e+04  1.903964e+07
20 0     12.500000  100350.308511  201146.414894  4.819245e+05  2.467080e+07
   1     13.333333  100354.583333  201049.083333  1.085667e+05  1.599050e+07
21 0      7.100840  100266.462185  200826.126050  1.006479e+06  1.964609e+07
   1      8.157895  100158.070175  200532.035088  6.143158e+05  2.155444e+07
22 0      6.117318  100205.743017  200652.497207  1.279689e+06  1.751834e+07
   1      4.736842  100145.105263  200474.500000  1.873997e+06  1.600784e+07
23 0      8.811475  100255.950820  200835.754098  9.189672e+05  2.054564e+07
   1      9.032258  100254.806452  200818.419355  9.475710e+05  2.566145e+07

               요일          주문량  holiday         월  실제_서울_최고기온  ...  \
시  핫딜유무                                                        ...
0  0     5.535714   202.612713      0.0  6.976190   30.469048  ...
1  0     5.203390   164.261986      0.0  6.864407   30.669492  ...
   1     5.671875   271.421305      0.0  7.281250   31.259375  ...
6  0     5.250000   412.379937      0.0  7.000000   30.052273  ...
   1     5.687500   303.255547      0.0  7.125000   31.756250  ...
7  0     5.357143   504.126551      0.0  7.047619   30.644048  ...
   1     6.000000   407.434304      0.0  7.666667   31.300000  ...
8  0     5.461538   625.182974      0.0  7.138462   30.636923  ...
   1     5.368421   185.012822      0.0  7.526316   31.784211  ...
9  0     5.575758   302.373041      0.0  7.181818   30.313131  ...
   1     5.000000   271.871169      0.0  7.333333   36.066667  ...
10 0     5.415254   195.363854      0.0  7.169492   30.912712  ...
   1     5.000000   680.647659      0.0  8.000000   28.300000  ...
11 0     5.387097   255.063899      0.0  7.209677   31.677419  ...
   1     5.125000   150.049537      0.0  6.625000   31.562500  ...
12 0     5.686275   388.710398      0.0  6.843137   30.350980  ...
   1     5.675676   239.488274      0.0  7.594595   30.681081  ...
13 0     5.710526   878.706683      0.0  7.368421   30.560526  ...
   1     5.304348   682.790471      0.0  6.934783   30.330435  ...
14 0     5.607143   517.603551      0.0  7.071429   30.096429  ...
   1     5.000000   177.508921      0.0  7.500000   35.687500  ...
15 0     5.443038   598.285026      0.0  6.759494   29.879747  ...
   1     5.206897   401.315095      0.0  7.793103   34.917241  ...
16 0     5.510000   544.201705      0.0  7.270000   31.326000  ...
   1     5.640000   238.905736      0.0  6.720000   30.484000  ...
17 0     5.739130   863.251595      0.0  6.913043   29.956522  ...
   1     5.000000  1223.672384      0.0  7.333333   33.066667  ...
18 0     5.612903   427.532311      0.0  7.080645   31.135484  ...
19 0     5.563830   253.716285      0.0  6.936170   30.592553  ...
   1     5.214286   394.613278      0.0  7.428571   32.885714  ...
20 0     5.595745   287.261002      0.0  7.138298   30.863830  ...
   1     5.000000   226.676975      0.0  7.333333   32.425000  ...
21 0     5.268908   128.104446      0.0  7.193277   31.007563  ...
   1     5.771930   183.404066      0.0  6.982456   30.808772  ...
22 0     5.430168    57.784367      0.0  6.927374   30.212291  ...
   1     5.710526    34.723338      0.0  7.710526   34.692105  ...
23 0     5.459016    83.347685      0.0  7.090164   30.384426  ...
   1     5.838710   113.057620      0.0  7.290323   32.474194  ...

         예보_일산_일최저기온  예보_수원_강수확률  예보_수원_강수량  예보_수원_일최고기온  예보_수원_일최저기온  \
시  핫딜유무
0  0       20.651042   17.740508   1.353540    30.251880    21.383185
1  0       20.485169   20.989464   2.861508    29.139161    21.280720
   1       21.760742   16.913007   0.823191    31.695724    22.386719
6  0       20.569602   19.319717   0.925239    29.627990    21.279830
   1       21.605469   18.184122   2.420230    31.085526    22.550781
7  0       20.520833   16.681145   1.307487    30.004386    21.154018
   1       19.145833    8.761261   0.035088    32.210526    20.041667
8  0       20.649038   15.019751   0.845344    30.480162    21.541346
   1       22.715461   32.894737   6.162396    30.231302    23.531250
9  0       20.368687   19.856675   1.377060    29.869219    21.097854
   1       21.062500    9.369369   0.087719    32.947368    21.979167
10 0       20.755826   21.750458   1.671833    30.043265    21.558792
   1       19.687500    8.175676   0.092105    29.842105    20.875000
11 0       20.813004   18.665541   1.369058    30.733022    21.542843
   1       20.484375   15.768581   0.855263    30.342105    21.445312
12 0       20.505515   15.652491   0.785217    30.220846    21.244485
   1       19.966216   14.501461   1.535917    30.610242    20.660473
13 0       20.518092   16.543385   0.843837    30.656510    21.347039
   1       20.600543   17.613102   1.619851    29.862700    21.289402
14 0       20.765625   19.191602   1.615602    30.037594    21.575893
   1       22.199219   19.332770   1.800987    33.003289    22.878906
15 0       19.634494   13.898392   0.994837    29.483678    20.429589
   1       23.799569   31.125349   3.514519    33.121597    24.359914
16 0       21.353125   16.858784   1.243947    30.782105    22.151875
   1       21.337500   17.954054   1.089474    30.360000    22.282500
17 0       20.027174   19.529965   1.539474    29.464531    20.663043
   1       21.489583   16.396396   1.184211    31.701754    22.281250
18 0       20.823589   17.946818   1.542233    30.664686    21.562500
19 0       20.218085   17.108971   1.150196    30.250840    20.868351
   1       23.303571   28.093629   5.033835    30.556391    24.080357
20 0       20.700798   17.147067   1.513018    30.505039    21.367686
   1       20.697917    9.667793   0.142544    31.548246    21.734375
21 0       21.144433   16.665910   1.328947    30.462185    21.910714
   1       20.324561   18.904694   0.724146    30.312096    20.941886
22 0       19.898045   16.013136   0.728903    29.817113    20.696578
   1       24.710526   33.790896   6.341759    32.421053    25.404605
23 0       20.784324   20.707244   1.543464    30.031924    21.567111
   1       22.110887   13.731473   1.250000    32.553480    22.737903

          Active Users          일      서울풍속      수원풍속      일산풍속
시  핫딜유무
0  0     133069.095238  19.011905  2.185698  1.777469  1.893605
1  0     130646.728814  20.627119  2.341216  1.980921  2.130027
   1     141370.937500  14.437500  2.159797  1.477988  1.672023
6  0     132473.704545  19.590909  2.173480  1.784628  1.860642
   1     139777.000000  18.375000  2.686571  2.059333  2.335684
7  0     134773.797619  17.214286  2.162645  1.727518  1.854424
   1     138705.000000  14.333333  1.961937  0.950450  1.150225
8  0     137297.892308  17.000000  2.285936  1.683565  1.863025
   1     141759.289474  22.842105  2.825853  2.265914  2.582095
9  0     132573.141414  20.353535  2.079580  1.532112  1.653529
   1     145084.666667   5.000000  2.081757  0.982658  1.257883
10 0     131926.881356  19.279661  2.385931  1.856648  1.998981
   1     151000.666667  19.333333  1.770946  0.882432  1.006982
11 0     137247.750000  14.758065  2.231937  1.609192  1.785958
   1     121899.750000  19.000000  2.128378  2.043919  1.895693
12 0     131857.166667  18.519608  2.058380  1.650404  1.753160
   1     140628.081081  19.108108  2.103616  1.446311  1.608893
13 0     134775.026316  19.368421  2.103876  1.606081  1.659193
   1     137684.086957  19.108696  2.406155  1.894653  2.138514
14 0     134179.357143  20.857143  2.273359  1.801086  1.958036
   1     145242.875000   7.500000  2.801182  1.969299  2.193792
15 0     131353.303797  19.683544  2.078909  1.826317  1.895706
   1     148185.206897  13.000000  3.566100  2.835415  3.082479
16 0     137054.750000  16.880000  2.291500  1.789351  1.853358
   1     138077.520000  22.040000  2.758649  2.090676  2.551514
17 0     128553.391304  18.217391  2.162867  1.722855  1.881727
   1     139869.333333  14.166667  2.320833  1.707207  1.794932
18 0     134637.274194  17.806452  2.305275  1.856811  1.982803
19 0     132260.765957  17.329787  2.184165  1.782777  1.891604
   1     143949.214286  19.928571  2.565878  1.943774  2.214286
20 0     135519.340426  17.234043  2.282605  1.772304  1.896701
   1     135980.166667  16.333333  1.515766  1.024550  1.049268
21 0     137434.361345  16.445378  2.317761  1.900295  1.956910
   1     133520.315789  16.596491  2.147048  1.411463  1.662127
22 0     132217.055866  19.128492  2.056002  1.560705  1.698841
   1     140422.789474  13.789474  3.463656  3.043243  3.197582
23 0     134609.483607  19.114754  2.193864  1.642933  1.793780
   1     138350.000000  15.387097  2.582323  2.112446  2.190126

[38 rows x 39 columns]

In [274]:
new_data_cj.loc[(new_data_cj["요일"]!=5)&(new_data_cj["요일"]!=6),:].groupby("핫딜유무")["주문량"].mean()

핫딜유무
0    318.832720
1    417.212395
Name: 주문량, dtype: float64

In [375]:
data = pd.read_csv("./정리데이터/prepared.csv")

In [405]:
data.groupby("핫딜유무").mean()

,노출(분),마더코드,상품코드,판매단가,취급액,요일,시,주문량,holiday,월,...,예보_수원_강수확률,예보_수원_강수량,예보_수원_일최고기온,예보_수원_일최저기온,Active Users,일,서울풍속,수원풍속,일산풍속,주차
핫딜유무,,,,,,,,,,,,,,,,,,,,,
0.0,11.737030,100370.918247,100370.918247,396132.164580,2.319746e+07,2.980143,13.967084,330.783299,0.014669,7.173524,...,23.678748,2.903234,30.188677,21.973824,141803.190519,17.561360,2.144461,1.629365,1.758969,5.025760
1.0,11.476081,100350.385591,100350.385591,387278.847262,2.275810e+07,3.144669,14.669741,334.653430,0.006916,7.229971,...,22.517447,2.975677,30.709149,22.238549,143081.944669,15.486455,2.163812,1.658618,1.797432,4.995389
2.0,13.659574,100406.335106,100406.335106,449917.553191,2.357651e+07,3.138298,13.138298,368.271805,0.063830,7.287234,...,27.093447,4.442334,30.939125,23.150598,147513.095745,16.393617,2.300517,1.748372,1.918519,5.329787